services:
#  traffic_control:
#    image: lukaszlach/docker-tc
#    container_name: traffic_control
#    network_mode: host
#    cap_add:
#      - NET_ADMIN
#    restart: always
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ./traffic-control:/var/docker-tc
  ollama:
    volumes:
      - ./ollama-data:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_FLASH_ATTENTION=1
    shm_size: '8gb'
    networks:
      - shared-net
 #   labels:
 #     com.docker-tc.enabled: "1"
 #     com.docker-tc.limit: "2mbps"
    deploy:
      resources:
        limits:
          memory: 60gb
          cpus: 8
        reservations:
          memory: 32gb
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ulimits:
      memlock: -1
      nofile:
        soft: 65536
        hard: 65536

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ./ollama-webui/data:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8877:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://ollama:11434
      - WEBUI_AUTH=True
      - ENABLE_BASE_MODELS_CACHE=true
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - shared-net
    labels:
      - swag_address=${SWAG_ADDRESS}
      - swag=enable
      - swag_port=8877
      - swag_url=chat.*

networks:
  shared-net:
    name: shared-net
    external: true
